### ISSUE TITLE
Video support and delete with a specific tag

### ISSUE THREAD

**Issue by morosakubek** [aranajhonny/ig-upload#3]
Hi,
The cool thing would be the ability to send video and remove media with a specific tag.

**Comment by aranajhonny** [comment]
Hi. I think the api I'm using allows it. In the next few days I will add it.

**Comment by owenroberts** [comment]
Hi, any update on video support?  Trying to post .mp4 file and get this error:
`Unhandled rejection RequestError: Uploaded image isn't in the right format`
Then `Uploading...` hangs...
Thanks :)

**Comment by Niek** [comment]
Another vote for video support

**Comment by LAMike310** [comment]
I would jump for joy for video support!

**Comment by aranajhonny** [comment]
When I created this project I did not think that people would use it, for my part I guarantee to add video support as soon as possible. @LAMike310

**Comment by aranajhonny** [comment]
sorry I have not had time to fix it, if you want you can collaborate to use https://github.com/jlobos/instagram-web-api/
