### ISSUE TITLE
pass login fields as parameters

### ISSUE THREAD

**Issue by manuhank** [aranajhonny/ig-upload#5]
is it posible to incorporate the username and password in the same login comand line?
it would be very usefull to have something like "ig-upload - login user pass" for scripting

**Comment by aranajhonny** [comment]
@HersonHN @zodman @manuhank Ready.

**Comment by aranajhonny** [comment]
sorry I have not had time to fix it, if you want you can collaborate to use https://github.com/jlobos/instagram-web-api/
